### ISSUE TITLE
part tab missing

### ISSUE THREAD

**Issue by qwert3356** [Open-Industry-Project/Open-Industry-Project#32]
![image](https://github.com/Open-Industry-Project/Open-Industry-Project/assets/29910345/31525195-a406-4d6d-a559-31fa9f2f5436)

I can't see the parts tab when I create a new project
Is this caused by an incorrect version of dot.net sdk installed?
The version of dot.net sdk I installed is dotnet-sdk-8.0.204

**Comment by qwert3356** [comment]
i looked video from discord group, i still can drag equipment in EquipmentAndDevices folder, thanks

**Comment by ryevdokimov** [comment]
The parts tab was added as part of v1.2 

https://github.com/Open-Industry-Project/Open-Industry-Project/releases/tag/v1.2.0
